experiment:
  name: dt_hiv_hi_random_shuffle
  task: hi
  dataset: hiv
fingerprint:
  types:
  - ecfp4
model:
  name: dt
  fixed:
    random_state: 42
  search:
    max_depth:
    - 3
    - 5
    - 8
    - 10
    - 15
    - 20
    - 30
    - null
    min_samples_split:
    - 2
    - 5
    - 10
    - 20
    - 50
    min_samples_leaf:
    - 1
    - 2
    - 5
    - 10
    - 20
    - 50
    criterion:
    - gini
    - entropy
    class_weight:
    - null
    - balanced
    max_features:
    - sqrt
    - log2
    - null
    ccp_alpha:
    - 0.0
    - 1.0e-05
    - 0.0001
    - 0.001
    - 0.01
cv:
  inner_k: 2
  scoring: average_precision
  search_strategy: grid
  random_state: 42
  holdout_val_fraction: 0.2
  inner_split_strategy: random_shuffle
artifacts:
  save_model: true
  save_complexity: true
  save_feature_importance: true
  save_cv_results: true
