experiment:
  name: dummy_kdr_lo
  task: lo
  dataset: kdr

fingerprint:
  type: ecfp4        

model:
  name: dummy
  fixed:
    strategy: mean  
  search: {}

cv:
  inner_k: 2
  scoring: neg_mean_absolute_error
  search_strategy: grid
  random_state: 42