experiment:
  name: lr_maccs_drd2_lo
  task: lo
  dataset: drd2

fingerprint:
  type: maccs

model:
  name: linreg
  search:
    fit_intercept: [true, false]

cv:
  inner_k: 2
  scoring: neg_mean_absolute_error
  search_strategy: grid
  random_state: 42